file(READ "${CMAKE_CURRENT_LIST_DIR}/workbench/mip-goldens.json" captures)
string(JSON count LENGTH "${captures}" rows)
math(EXPR last "${count} - 1")
set(output_dir "${CMAKE_CURRENT_BINARY_DIR}/mip-goldens")
file(MAKE_DIRECTORY "${output_dir}")

function(run_checked)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Golden command failed (${result}): ${ARGV}\n${output}\n${error}")
  endif()
endfunction()

foreach(index RANGE 0 ${last})
  string(JSON row GET "${captures}" rows ${index})
  foreach(key IN ITEMS width height source_bgra mip_function tiled mip_filter)
    string(JSON ${key} GET "${row}" ${key})
  endforeach()
  string(JSON alpha ERROR_VARIABLE no_alpha GET "${row}" alpha)
  if(no_alpha OR alpha)
    set(alpha 1)
  else()
    set(alpha 0)
  endif()
  if(tiled)
    set(tiled true)
  else()
    set(tiled false)
  endif()
  if(mip_function EQUAL 2)
    set(mip_function color-noise)
    set(function_name ColorNoise)
  else()
    set(mip_function filter)
    set(function_name Filter)
  endif()
  if(mip_filter EQUAL 2)
    set(mip_filter kaiser)
    set(filter_name Kaiser)
  else()
    set(mip_filter box)
    set(filter_name Box)
  endif()
  string(JSON levels LENGTH "${row}" levels)
  math(EXPR last_level "${levels} - 1")
  set(expected "")
  foreach(level RANGE 0 ${last_level})
    string(JSON bgra GET "${row}" levels ${level} bgra)
    string(APPEND expected "${bgra}")
  endforeach()
  set(source "${output_dir}/${index}.tga")
  set(output "${output_dir}/${index}.edds")
  set(metadata "${output}.meta")
  run_checked("${FIXTURE}" --mip-source "${source}" ${width} ${height} ${alpha} "${source_bgra}")
  # Each removal boundary must preserve exactly the remaining captured levels.
  foreach(removed RANGE 0 ${last_level})
    run_checked("${CLI}" edds convert --machine --protocol 1 --input "${source}" --output "${output}"
      --format-compress copy --mipmap-function ${mip_function} --mipmap-filter ${mip_filter}
      --tiled-texture ${tiled} --remove-mips ${removed} --metadata "${metadata}"
      --resource-name "goldens/${index}.edds" --source-file "${index}.tga" --guid 0123456789ABCDEF)
    run_checked("${REFERENCE_READER}" --golden "${output}" ${width} ${height} ${levels} "${expected}" ${removed})
  endforeach()
  execute_process(COMMAND "${CLI}" edds inspect --machine --protocol 1 --input "${output}"
    --metadata "${metadata}" RESULT_VARIABLE inspected OUTPUT_VARIABLE inspection)
  string(JSON actual_function GET "${inspection}" metadata recipe MipMapFunction)
  string(JSON actual_tiled GET "${inspection}" metadata recipe TiledTexture)
  if(NOT inspected EQUAL 0 OR NOT actual_function STREQUAL function_name OR
     (actual_tiled AND NOT tiled) OR (NOT actual_tiled AND tiled))
    message(FATAL_ERROR "Golden metadata lost its profile: ${inspection}")
  endif()
  # Batch uses the canonical JSON profile, not convert's command-line spelling.
  set(batch_output "${output_dir}/${index}-batch.edds")
  set(batch_input "${output_dir}/${index}.ndjson")
  set(profile "{\"TargetFormat\":\"EnfusionDDS\",\"FormatCompress\":\"Copy\",\"CompressTreshold\":80,\"RemoveMips\":0,\"Conversion\":\"None\",\"ConversionQuality\":1,\"Swizzling\":\"None\",\"ContainsMips\":false,\"GenerateMips\":true,\"Normalize\":false,\"MipMapFunction\":\"${function_name}\",\"MipMapFilter\":\"${filter_name}\",\"TiledTexture\":${tiled}}")
  file(WRITE "${batch_input}"
    "{\"protocolVersion\":1,\"kind\":\"batch\",\"jobCount\":1}\n"
    "{\"protocolVersion\":1,\"kind\":\"job\",\"id\":\"golden\",\"input\":\"${source}\",\"output\":\"${batch_output}\",\"metadata\":null,\"identity\":null,\"profile\":${profile},\"expected\":null}\n"
    "{\"protocolVersion\":1,\"kind\":\"end\"}\n")
  execute_process(COMMAND "${CLI}" edds batch --machine --protocol 1 INPUT_FILE "${batch_input}"
    RESULT_VARIABLE batch_result OUTPUT_VARIABLE batch_stdout ERROR_VARIABLE batch_error)
  if(NOT batch_result EQUAL 0 OR NOT batch_stdout MATCHES "\"converted\":1")
    message(FATAL_ERROR "Golden batch failed: ${batch_stdout}\n${batch_error}")
  endif()
  run_checked("${REFERENCE_READER}" --golden "${batch_output}" ${width} ${height} ${levels} "${expected}" 0)
  # An inactive ColorNoise must refuse without replacing an existing destination.
  file(SHA256 "${batch_output}" before_refusal)
  execute_process(COMMAND "${CLI}" edds convert --machine --protocol 1 --input "${source}"
    --output "${batch_output}" --generate-mips false --mipmap-function color-noise
    --tiled-texture ${tiled} RESULT_VARIABLE refused OUTPUT_VARIABLE refusal ERROR_QUIET)
  string(JSON code GET "${refusal}" error code)
  file(SHA256 "${batch_output}" after_refusal)
  if(NOT refused EQUAL 4 OR NOT code STREQUAL "unsupported-combination" OR
      NOT before_refusal STREQUAL after_refusal)
    message(FATAL_ERROR "Inactive ColorNoise was not refused atomically: ${refusal}")
  endif()
endforeach()
message(STATUS "${count} Workbench captures matched every level and RemoveMips boundary")
