file(READ "${CMAKE_CURRENT_LIST_DIR}/workbench/swizzle-goldens.json" captures)
string(JSON count LENGTH "${captures}" rows)
math(EXPR last "${count} - 1")
set(output_dir "${CMAKE_CURRENT_BINARY_DIR}/swizzle-goldens")
file(MAKE_DIRECTORY "${output_dir}")

function(run_checked)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Swizzle command failed (${result}): ${ARGV}\n${output}\n${error}")
  endif()
endfunction()

foreach(index RANGE 0 ${last})
  string(JSON row GET "${captures}" rows ${index})
  foreach(key IN ITEMS width height source_bgra swizzling wire alpha generate normalize mip_function mip_filter tiled remove conversion)
    string(JSON ${key} GET "${row}" ${key})
  endforeach()
  set(incompatible FALSE)
  if((swizzling STREQUAL "TerrainLayerTexture" OR swizzling STREQUAL "TerrainSuperTexture") AND
     (conversion EQUAL 0 OR conversion EQUAL 1) AND NOT generate)
    set(incompatible TRUE)
  endif()
  foreach(key IN ITEMS generate normalize tiled)
    if(${key})
      set(${key} true)
    else()
      set(${key} false)
    endif()
  endforeach()
  if(alpha)
    set(alpha 1)
  else()
    set(alpha 0)
  endif()
  if(mip_function EQUAL 1)
    set(mip_function normalize)
    set(function_name Normalize)
  else()
    set(mip_function filter)
    set(function_name Filter)
  endif()
  if(mip_filter EQUAL 2)
    set(mip_filter kaiser)
    set(filter_name Kaiser)
  else()
    set(mip_filter box)
    set(filter_name Box)
  endif()
  if(NOT conversion EQUAL 0)
    set(conversion_names None DXTCompression RedHQCompression RedGreenHQCompression RedGreen unused Red unused ColorHQCompression)
    set(conversion_wires none dxt-compression red-hq-compression red-green-hq-compression red-green unused red unused color-hq-compression)
    list(GET conversion_names ${conversion} conversion_name)
    list(GET conversion_wires ${conversion} conversion_wire)
    string(JSON output_format GET "${row}" encoder_format)
    if(output_format EQUAL 71)
      set(pixel_format DXT1)
    elseif(output_format EQUAL 77)
      set(pixel_format DXT5)
    elseif(output_format EQUAL 61)
      set(pixel_format R8)
    elseif(output_format EQUAL 49)
      set(pixel_format RG8)
    elseif(output_format EQUAL 80)
      set(pixel_format BC4)
    elseif(output_format EQUAL 83)
      set(pixel_format BC5)
    elseif(output_format EQUAL 98)
      set(pixel_format BC7)
    else()
      message(FATAL_ERROR "Unrecognized captured DXGI format ${output_format}")
    endif()
  else()
    set(conversion_wire none)
    set(conversion_name None)
    string(JSON output_format GET "${row}" output_format)
    if(output_format EQUAL 88)
      set(pixel_format BGRX8)
    else()
      set(pixel_format BGRA8)
    endif()
  endif()
  string(JSON levels LENGTH "${row}" levels)
  math(EXPR last_level "${levels} - 1")
  set(expected "")
  foreach(level RANGE 0 ${last_level})
    string(JSON bgra GET "${row}" levels ${level} bgra)
    string(APPEND expected "${bgra}")
  endforeach()
  set(source "${output_dir}/${index}.tga")
  set(output "${output_dir}/${index}.edds")
  set(metadata "${output}.meta")
  run_checked("${FIXTURE}" --mip-source "${source}" ${width} ${height} ${alpha} "${source_bgra}")
  file(SHA256 "${source}" source_before)
  if(incompatible)
    execute_process(COMMAND "${CLI}" convert --machine --protocol 1 --input "${source}" --output "${output}"
      --swizzling "${wire}" --generate-mips false RESULT_VARIABLE refused OUTPUT_VARIABLE refusal ERROR_QUIET)
    if(NOT refused EQUAL 4 OR NOT refusal MATCHES "unsupported-combination")
      message(FATAL_ERROR "Inactive terrain mips must refuse: ${refusal}")
    endif()
    continue()
  endif()
  run_checked("${CLI}" convert --machine --protocol 1 --input "${source}" --output "${output}"
    --format-compress copy --swizzling "${wire}" --generate-mips ${generate}
    --normalize ${normalize} --mipmap-function ${mip_function} --mipmap-filter ${mip_filter}
    --tiled-texture ${tiled} --remove-mips ${remove} --conversion ${conversion_wire}
    --metadata "${metadata}" --resource-name "swizzling/${index}.edds"
    --source-file "${index}.tga" --guid 0123456789ABCDEF)
  string(JSON width GET "${row}" levels 0 width)
  string(JSON height GET "${row}" levels 0 height)
  run_checked("${REFERENCE_READER}" --swizzle "${output}" ${width} ${height} ${levels} "${expected}" ${pixel_format})
  execute_process(COMMAND "${CLI}" inspect --machine --protocol 1 --input "${output}" --metadata "${metadata}"
    RESULT_VARIABLE inspected OUTPUT_VARIABLE inspection)
  string(JSON actual GET "${inspection}" metadata recipe Swizzling)
  if(NOT inspected EQUAL 0 OR NOT actual STREQUAL swizzling)
    message(FATAL_ERROR "Swizzling metadata did not round-trip: ${inspection}")
  endif()
  # Result preview reads the actual output at every mip; source pixels stay in the source file.
  foreach(level RANGE 0 ${last_level})
    run_checked("${CLI}" preview --machine --protocol 1 --input "${output}" --mip ${level})
  endforeach()
  set(batch_output "${output_dir}/${index}-batch.edds")
  set(batch_input "${output_dir}/${index}.ndjson")
  set(profile "{\"TargetFormat\":\"EnfusionDDS\",\"FormatCompress\":\"Copy\",\"CompressTreshold\":80,\"RemoveMips\":${remove},\"Conversion\":\"${conversion_name}\",\"ConversionQuality\":1,\"Swizzling\":\"${swizzling}\",\"ContainsMips\":false,\"GenerateMips\":${generate},\"Normalize\":${normalize},\"MipMapFunction\":\"${function_name}\",\"MipMapFilter\":\"${filter_name}\",\"TiledTexture\":${tiled}}")
  file(WRITE "${batch_input}"
    "{\"protocolVersion\":1,\"kind\":\"batch\",\"jobCount\":1}\n"
    "{\"protocolVersion\":1,\"kind\":\"job\",\"id\":\"swizzle\",\"input\":\"${source}\",\"output\":\"${batch_output}\",\"metadata\":null,\"identity\":null,\"profile\":${profile},\"expected\":null}\n"
    "{\"protocolVersion\":1,\"kind\":\"end\"}\n")
  execute_process(COMMAND "${CLI}" batch --machine --protocol 1 INPUT_FILE "${batch_input}"
    RESULT_VARIABLE batch_result OUTPUT_VARIABLE batch_stdout ERROR_VARIABLE batch_error)
  if(NOT batch_result EQUAL 0 OR NOT batch_stdout MATCHES "\"converted\":1")
    message(FATAL_ERROR "Swizzle batch failed: ${batch_stdout}\n${batch_error}")
  endif()
  run_checked("${REFERENCE_READER}" --swizzle "${batch_output}" ${width} ${height} ${levels} "${expected}" ${pixel_format})
  file(SHA256 "${source}" source_after)
  if(NOT source_before STREQUAL source_after)
    message(FATAL_ERROR "Conversion or preview modified the source")
  endif()
endforeach()

# Refusals must leave a previously valid registered pair byte-for-byte intact.
set(guard_source "${output_dir}/0.tga")
set(guard_output "${output_dir}/0.edds")
set(guard_metadata "${guard_output}.meta")
file(SHA256 "${guard_output}" before_output)
file(SHA256 "${guard_metadata}" before_metadata)
function(refuse_preserving_pair expected_code)
  execute_process(COMMAND "${CLI}" convert --machine --protocol 1 --input "${guard_source}"
    --output "${guard_output}" --metadata "${guard_metadata}" --resource-name swizzling/0.edds
    --source-file 0.tga --guid 0123456789ABCDEF ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE response ERROR_QUIET)
  file(SHA256 "${guard_output}" after_output)
  file(SHA256 "${guard_metadata}" after_metadata)
  if(result EQUAL 0 OR NOT response MATCHES "${expected_code}" OR
      NOT before_output STREQUAL after_output OR NOT before_metadata STREQUAL after_metadata)
    message(FATAL_ERROR "Swizzle refusal damaged the pair or returned the wrong error: ${response}")
  endif()
endfunction()
refuse_preserving_pair(unsupported-setting --swizzling not-a-swizzle)
refuse_preserving_pair(unsupported-combination --swizzling terrain-layer-texture --generate-mips false)
refuse_preserving_pair(unsupported-combination --swizzling terrain-super-texture --contains-mips true --generate-mips false)
refuse_preserving_pair(unsupported-combination --swizzling ambient-specular-map-ga --remove-mips 1)
refuse_preserving_pair(remove-mips-out-of-range --swizzling normal-map-nohq --remove-mips 14)
configure_file("${guard_source}" "${guard_source}.backup" COPYONLY)
file(WRITE "${guard_source}" "short")
foreach(wire IN ITEMS terrain-layer-texture terrain-super-texture terrain-normal-specular-syxx
    alpha-to-rgb smdi-to-gs normal-map-nohq normal-map-ga normal-specular-map-xyzs ambient-specular-map-ga)
  refuse_preserving_pair(invalid-input --swizzling "${wire}")
endforeach()
configure_file("${guard_source}.backup" "${guard_source}" COPYONLY)

# The last captured profile is AmbientSpecular with RemoveMips=1: RGB cannot supply its alpha,
# while an RGBA item alongside it succeeds. The batch keeps one full profile for both jobs.
set(mixed "${output_dir}/mixed.ndjson")
file(WRITE "${mixed}" "{\"protocolVersion\":1,\"kind\":\"batch\",\"jobCount\":2}\n")
foreach(item IN ITEMS 5 8)
  file(APPEND "${mixed}" "{\"protocolVersion\":1,\"kind\":\"job\",\"id\":\"${item}\",\"input\":\"${output_dir}/${item}.tga\",\"output\":\"${output_dir}/mixed-${item}.edds\",\"metadata\":null,\"identity\":null,\"profile\":${profile},\"expected\":null}\n")
endforeach()
file(APPEND "${mixed}" "{\"protocolVersion\":1,\"kind\":\"end\"}\n")
execute_process(COMMAND "${CLI}" batch --machine --protocol 1 INPUT_FILE "${mixed}"
  RESULT_VARIABLE mixed_result OUTPUT_VARIABLE mixed_output ERROR_VARIABLE mixed_error)
if(NOT mixed_result EQUAL 0 OR NOT mixed_output MATCHES "\"converted\":1" OR
    NOT mixed_output MATCHES "\"failed\":1" OR NOT mixed_output MATCHES "unsupported-combination")
  message(FATAL_ERROR "Mixed source channels were not isolated: ${mixed_output}\n${mixed_error}")
endif()
